# Generated by Django 4.2.5 on 2025-01-31 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogAdoptionapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='owner_name',
        ),
    ]
