# Generated by Django 4.2.5 on 2025-01-31 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogAdoptionapp', '0002_remove_dog_contact_remove_dog_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogAdoptionapp.dog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
