# Generated by Django 4.2.5 on 2025-01-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogAdoptionapp', '0003_adoptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
