# Generated by Django 4.2.5 on 2025-02-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogAdoptionapp', '0011_message_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
